var KinkyDungeonMapParams = [
	{
		"openness" : 3, // Openness of rooms
		"density" : 3, // Density of tunnels (inverse of room spawn chance)
		"doodadchance" : 0.16,
		"brightness" : 8,
		"chestcount" : 2,
		"doorchance" : 0.67,
	},
	{
		"openness" : 0,
		"density" : 2,
		"doodadchance" : 0.11,
		"brightness" : 6,
		"chestcount" : 3,
		"doorchance" : 0.9,
	},
	{
		"openness" : 2,
		"density" : 5,
		"doodadchance" : 0.15,
		"brightness" : 7,
		"chestcount" : 4,
		"doorchance" : 0.2,
	},
	{
		"openness" : 2,
		"density" : 0,
		"doodadchance" : 0.13,
		"brightness" : 8,
		"chestcount" : 4,
		"doorchance" : 0.9,
	},
	{
		"openness" : 4,
		"density" : 4,
		"doodadchance" : 0.15,
		"brightness" : 7,
		"chestcount" : 5,
		"doorchance" : 0.05,
	},
	{
		"openness" : 1,
		"density" : 1,
		"doodadchance" : 0.05,
		"brightness" : 8,
		"chestcount" : 5,
		"doorchance" : 0.67,
	},
	{
		"openness" : 4,
		"density" : 2,
		"doodadchance" : 0.13,
		"brightness" : 5,
		"chestcount" : 5,
		"doorchance" : 0.0,
	},
	{
		"openness" : 2,
		"density" : 1,
		"doodadchance" : 0.12,
		"brightness" : 4,
		"chestcount" : 5,
		"doorchance" : 0.8,
	},
	{
		"openness" : 4,
		"density" : 0,
		"doodadchance" : 0.12,
		"brightness" : 8,
		"chestcount" : 6,
		"doorchance" : 1.0,
	},
	{
		"openness" : 2,
		"density" : 1,
		"doodadchance" : 0.08,
		"brightness" : 4,
		"chestcount" : 6,
		"doorchance" : 1.0,
	},
	{
		"openness" : 10,
		"density" : 0,
		"doodadchance" : 0.05,
		"brightness" : 100,
		"chestcount" : 0,
		"doorchance" : 1.0,
	},
	
];