name: Asset check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  asset-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BondageClub/Tools/Node
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - name: Run TypeScript
      run: |
       npm run -s assetcheck-typescript -- --pretty false | sed -E 's/^([^ ][^\(]*)\(([0-9]+),([0-9]+)\): (.*)$/\0\n::error file=\1,line=\2,col=\3::\4/' | sed -z 's/\n  /%0A  /'
      shell: bash
    - name: Run Asset check
      run: npm run -s assetcheck
